//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NerdyNodeParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="NerdyNodeParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface INerdyNodeParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] NerdyNodeParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] NerdyNodeParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] NerdyNodeParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] NerdyNodeParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.funcdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncdeclaration([NotNull] NerdyNodeParser.FuncdeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.funcdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncdeclaration([NotNull] NerdyNodeParser.FuncdeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.paramdecllist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamdecllist([NotNull] NerdyNodeParser.ParamdecllistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.paramdecllist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamdecllist([NotNull] NerdyNodeParser.ParamdecllistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamdecl([NotNull] NerdyNodeParser.ParamdeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamdecl([NotNull] NerdyNodeParser.ParamdeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] NerdyNodeParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] NerdyNodeParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.forstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForstmt([NotNull] NerdyNodeParser.ForstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.forstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForstmt([NotNull] NerdyNodeParser.ForstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstmt([NotNull] NerdyNodeParser.IfstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstmt([NotNull] NerdyNodeParser.IfstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] NerdyNodeParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] NerdyNodeParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] NerdyNodeParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] NerdyNodeParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] NerdyNodeParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] NerdyNodeParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] NerdyNodeParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] NerdyNodeParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] NerdyNodeParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] NerdyNodeParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] NerdyNodeParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] NerdyNodeParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.arrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrow([NotNull] NerdyNodeParser.ArrowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.arrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrow([NotNull] NerdyNodeParser.ArrowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] NerdyNodeParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] NerdyNodeParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.numop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumop([NotNull] NerdyNodeParser.NumopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.numop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumop([NotNull] NerdyNodeParser.NumopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.boolop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolop([NotNull] NerdyNodeParser.BoolopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.boolop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolop([NotNull] NerdyNodeParser.BoolopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.graphop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphop([NotNull] NerdyNodeParser.GraphopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.graphop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphop([NotNull] NerdyNodeParser.GraphopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.graph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraph([NotNull] NerdyNodeParser.GraphContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.graph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraph([NotNull] NerdyNodeParser.GraphContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.nodeset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNodeset([NotNull] NerdyNodeParser.NodesetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.nodeset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNodeset([NotNull] NerdyNodeParser.NodesetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.edgeset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEdgeset([NotNull] NerdyNodeParser.EdgesetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.edgeset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEdgeset([NotNull] NerdyNodeParser.EdgesetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.identlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentlist([NotNull] NerdyNodeParser.IdentlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.identlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentlist([NotNull] NerdyNodeParser.IdentlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.funccall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunccall([NotNull] NerdyNodeParser.FunccallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.funccall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunccall([NotNull] NerdyNodeParser.FunccallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.paramlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamlist([NotNull] NerdyNodeParser.ParamlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.paramlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamlist([NotNull] NerdyNodeParser.ParamlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.graphfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphfunc([NotNull] NerdyNodeParser.GraphfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.graphfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphfunc([NotNull] NerdyNodeParser.GraphfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.addtograph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddtograph([NotNull] NerdyNodeParser.AddtographContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.addtograph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddtograph([NotNull] NerdyNodeParser.AddtographContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.returnstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnstmt([NotNull] NerdyNodeParser.ReturnstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.returnstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnstmt([NotNull] NerdyNodeParser.ReturnstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] NerdyNodeParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] NerdyNodeParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.draw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDraw([NotNull] NerdyNodeParser.DrawContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.draw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDraw([NotNull] NerdyNodeParser.DrawContext context);
}
