//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NerdyNodeParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INerdyNodeParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class NerdyNodeParserBaseListener : INerdyNodeParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] NerdyNodeParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] NerdyNodeParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] NerdyNodeParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] NerdyNodeParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.funcdeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncdeclaration([NotNull] NerdyNodeParser.FuncdeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.funcdeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncdeclaration([NotNull] NerdyNodeParser.FuncdeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.paramdecllist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamdecllist([NotNull] NerdyNodeParser.ParamdecllistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.paramdecllist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamdecllist([NotNull] NerdyNodeParser.ParamdecllistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.paramdecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamdecl([NotNull] NerdyNodeParser.ParamdeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.paramdecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamdecl([NotNull] NerdyNodeParser.ParamdeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] NerdyNodeParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] NerdyNodeParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.forstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstmt([NotNull] NerdyNodeParser.ForstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.forstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstmt([NotNull] NerdyNodeParser.ForstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] NerdyNodeParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] NerdyNodeParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] NerdyNodeParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] NerdyNodeParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] NerdyNodeParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] NerdyNodeParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] NerdyNodeParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] NerdyNodeParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] NerdyNodeParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] NerdyNodeParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] NerdyNodeParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] NerdyNodeParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] NerdyNodeParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] NerdyNodeParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.arrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrow([NotNull] NerdyNodeParser.ArrowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.arrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrow([NotNull] NerdyNodeParser.ArrowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] NerdyNodeParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] NerdyNodeParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.numop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumop([NotNull] NerdyNodeParser.NumopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.numop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumop([NotNull] NerdyNodeParser.NumopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.boolop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolop([NotNull] NerdyNodeParser.BoolopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.boolop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolop([NotNull] NerdyNodeParser.BoolopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.graphop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphop([NotNull] NerdyNodeParser.GraphopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.graphop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphop([NotNull] NerdyNodeParser.GraphopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.graph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraph([NotNull] NerdyNodeParser.GraphContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.graph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraph([NotNull] NerdyNodeParser.GraphContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.nodeset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNodeset([NotNull] NerdyNodeParser.NodesetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.nodeset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNodeset([NotNull] NerdyNodeParser.NodesetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.edgeset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEdgeset([NotNull] NerdyNodeParser.EdgesetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.edgeset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEdgeset([NotNull] NerdyNodeParser.EdgesetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.identlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentlist([NotNull] NerdyNodeParser.IdentlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.identlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentlist([NotNull] NerdyNodeParser.IdentlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.funccall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunccall([NotNull] NerdyNodeParser.FunccallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.funccall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunccall([NotNull] NerdyNodeParser.FunccallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.paramlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamlist([NotNull] NerdyNodeParser.ParamlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.paramlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamlist([NotNull] NerdyNodeParser.ParamlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.graphfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphfunc([NotNull] NerdyNodeParser.GraphfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.graphfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphfunc([NotNull] NerdyNodeParser.GraphfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.addtograph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddtograph([NotNull] NerdyNodeParser.AddtographContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.addtograph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddtograph([NotNull] NerdyNodeParser.AddtographContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.returnstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnstmt([NotNull] NerdyNodeParser.ReturnstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.returnstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnstmt([NotNull] NerdyNodeParser.ReturnstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint([NotNull] NerdyNodeParser.PrintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint([NotNull] NerdyNodeParser.PrintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NerdyNodeParser.draw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDraw([NotNull] NerdyNodeParser.DrawContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NerdyNodeParser.draw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDraw([NotNull] NerdyNodeParser.DrawContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
